<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libraries\Aether.Physics2D\Physics2D\Aether.Physics2D.NETSTANDARD2_0.csproj" />
    <ProjectReference Include="..\..\..\src\domain\VoidHuntersRevived.Domain.Physics\VoidHuntersRevived.Domain.Physics.csproj" />
    <ProjectReference Include="..\..\..\src\domain\VoidHuntersRevived.Domain.Pieces\VoidHuntersRevived.Domain.Pieces.csproj" />
    <ProjectReference Include="..\..\..\src\domain\VoidHuntersRevived.Domain.Ships\VoidHuntersRevived.Domain.Ships.csproj" />
    <ProjectReference Include="..\..\..\src\domain\VoidHuntersRevived.Domain.Teams\VoidHuntersRevived.Domain.Teams.csproj" />
    <ProjectReference Include="..\..\common\VoidHuntersRevived.Tests.Common.Physics\VoidHuntersRevived.Tests.Common.Physics.csproj" />
    <ProjectReference Include="..\..\common\VoidHuntersRevived.Tests.Common.Simulations\VoidHuntersRevived.Tests.Common.Simulations.csproj" />
    <ProjectReference Include="..\..\registration\VoidHuntersRevived.Tests.Registration.Physics\VoidHuntersRevived.Tests.Registration.Physics.csproj" />
    <ProjectReference Include="..\..\registration\VoidHuntersRevived.Tests.Registration.Pieces\VoidHuntersRevived.Tests.Registration.Pieces.csproj" />
    <ProjectReference Include="..\..\registration\VoidHuntersRevived.Tests.Registration.Ships\VoidHuntersRevived.Tests.Registration.Ships.csproj" />
    <ProjectReference Include="..\..\registration\VoidHuntersRevived.Tests.Registration.Simulations\VoidHuntersRevived.Tests.Registration.Simulations.csproj" />
    <ProjectReference Include="..\..\registration\VoidHuntersRevived.Tests.Registration.Teams\VoidHuntersRevived.Tests.Registration.Teams.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
