// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoidHuntersRevived.Utilities.Server.Web.Data;

namespace VoidHuntersRevived.Utilities.Server.Web.Migrations
{
    [DbContext(typeof(VoidHuntersRevivedServerWebContext))]
    [Migration("20210408214518_UpdateRelease")]
    partial class AddReleases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VoidHuntersRevived.Utilities.Server.Web.Models.Release", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Major")
                        .HasColumnType("bigint");

                    b.Property<long>("Minor")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubMinor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Release");
                });
#pragma warning restore 612, 618
        }
    }
}
