<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\Guppy\tests\Guppy.Tests.Common\Guppy.Tests.Common.csproj" />
    <ProjectReference Include="..\VoidHuntersRevived.Tests.Domain.Simulations.Common\VoidHuntersRevived.Tests.Domain.Simulations.Common.csproj" />
  </ItemGroup>

</Project>
