<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\libraries\Guppy\src\game\Guppy.Game.MonoGame.Common\Guppy.Game.MonoGame.Common.csproj" />
    <ProjectReference Include="..\VoidHuntersRevived.Domain.Common\VoidHuntersRevived.Domain.Common.csproj" />
    <ProjectReference Include="..\VoidHuntersRevived.Domain.Entities.Common\VoidHuntersRevived.Domain.Entities.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.Xna.Framework.Graphics.PrimitiveType">
      <Alias>PrimitiveTypeEnum</Alias>
    </Using>
  </ItemGroup>
	
</Project>
