<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Common\VoidHuntersRevived.Domain.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Physics.Common\VoidHuntersRevived.Domain.Physics.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Pieces.Common\VoidHuntersRevived.Domain.Pieces.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Ships.Common\VoidHuntersRevived.Domain.Ships.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Teams.Common\VoidHuntersRevived.Domain.Teams.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Common\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Descriptors\**" />
    <EmbeddedResource Remove="Descriptors\**" />
    <None Remove="Descriptors\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Content\Common\Pieces\base.hull.json" />
    <None Remove="Content\Common\Pieces\base.thruster.json" />
    <None Remove="Content\Common\primitives.json" />
    <None Remove="Content\Common\Primitives\primitive.visible.hull.square.json" />
    <None Remove="Content\Common\teams.json" />
    <None Remove="Content\Common\Teams\team.00.json" />
    <None Remove="Content\Common\Teams\team.01.json" />
    <None Remove="Content\Common\Primitives\visible.hull.square.json" />
    <None Remove="Content\Common\Primitives\visible.hull.triangle.json" />
    <None Remove="Content\Common\Primitives\visible.thruster.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Content\Common\Pieces\base.hull.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
