<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <MonoGamePlatform>DesktopGL</MonoGamePlatform>
  </PropertyGroup>
	
  <Import Project="..\..\..\libraries\Guppy\libraries\MonoGame\Tools\MonoGame.Content.Builder.Task\MonoGame.Content.Builder.Task.props" />
  <Import Project="..\..\..\libraries\Guppy\libraries\MonoGame\Tools\MonoGame.Content.Builder.Task\MonoGame.Content.Builder.Task.targets" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\libraries\Guppy\src\game\Guppy.Game.Graphics.Common\Guppy.Game.Graphics.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Common\VoidHuntersRevived.Domain.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Physics.Common\VoidHuntersRevived.Domain.Physics.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Pieces.Common\VoidHuntersRevived.Domain.Pieces.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Ships.Common\VoidHuntersRevived.Domain.Ships.Common.csproj" />
    <ProjectReference Include="..\..\domain\VoidHuntersRevived.Domain.Teams.Common\VoidHuntersRevived.Domain.Teams.Common.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="Content\Common\**\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Content\Common\Shaders\Compiled\*.mgfx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Content\Common\Shaders\*.fx" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Content\Common\bodies.json" />
	  <None Remove="Content\Common\Bodies\body.hull.square.json" />
	  <None Remove="Content\Common\Bodies\body.hull.triangle.json" />
	  <None Remove="Content\Common\Bodies\body.thruster.json" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Content\Common\Entities\" />
	</ItemGroup>

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition=" '$(OS)' == 'Windows_NT' ">
		<Exec Command="pwsh.exe -ExecutionPolicy Bypass -NoProfile -NonInteractive -File $(SolutionDir)scripts\compile-fx.ps1 &quot;$(ProjectDir)Content\Common\Shaders&quot; &quot;$(ProjectDir)Content\Common\Shaders\Compiled&quot;" />
	</Target>
</Project>
